[versions]
jackson = "2.20.0"
jackson3 = "3.0.1"
log4j = "2.25.2"
jline = "3.30.6"
maven = "1.9.24"

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
git = { id = "com.gorylenko.gradle-git-properties", version = "2.5.4" }
versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }

[libraries]
apache-commons-compress = { module = "org.apache.commons:commons-compress", version = "1.28.0" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.19.0" }
commons-io = { module = "commons-io:commons-io", version = "2.20.0" }
fastutil = { module = "it.unimi.dsi:fastutil", version = "8.5.18" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
guava = { module = "com.google.guava:guava", version = "33.5.0-jre" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-guava = { module = "com.fasterxml.jackson.datatype:jackson-datatype-guava", version.ref = "jackson" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-core = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson3" }
jackson-guava = { module = "tools.jackson.datatype:jackson-datatype-guava", version.ref = "jackson3" }
javax-annotations = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
jline-reader = { module = "org.jline:jline-reader", version.ref = "jline" }
jline-terminal = { module = "org.jline:jline-terminal-jni", version.ref = "jline" }
jline-terminal-ffm = { module = "org.jline:jline-terminal-ffm", version.ref = "jline" }
jopt = { module = "net.sf.jopt-simple:jopt-simple", version = "5.0.4" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "6.0.1" }
jwt = { module = "com.nimbusds:nimbus-jose-jwt", version = "10.5" }
leveldb-mcpe-jni = { module = "net.daporkchop:leveldb-mcpe-jni", version = "0.0.10-SNAPSHOT" }
leveldb-natives = { module = "net.daporkchop.lib:natives", version = "0.5.8-SNAPSHOT" }
lmax-disruptor = { module = "com.lmax:disruptor", version = "4.0.0" }
lmbda = { group = "org.lanternpowered", name = "lmbda", version = "2.0.0" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.42" }
maven-provider = { group = "org.apache.maven", name = "maven-resolver-provider", version = "3.9.11" }
maven-connector = { group = "org.apache.maven.resolver", name = "maven-resolver-connector-basic", version.ref = "maven" }
maven-http = { group = "org.apache.maven.resolver", name = "maven-resolver-transport-http", version.ref = "maven" }
minecrell-console = { module = "net.minecrell:terminalconsoleappender", version = "1.3.0" }
org-cloudburstmc-upnp = { module = "org.cloudburstmc:upnp", version = "1.1.1" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
snakeyaml = { module = "org.yaml:snakeyaml", version = "2.5" }
snakeyaml-engine = { module = "org.snakeyaml:snakeyaml-engine", version = "2.10" }
snappy = { module = "org.xerial.snappy:snappy-java", version = "1.1.10.8" }
zero-allocation-hashing = { module = "net.openhft:zero-allocation-hashing", version = "0.16" }
zstd = { module = "com.github.luben:zstd-jni", version = "1.5.7-6" }
